#!/bin/bash
LOCAL=$(pwd)
GODOTCPPCLIDIR=$(pwd)

echo 'export PATH="'$LOCAL'/bin:$PATH"' >> ~/.bashrc
echo 'export GODOTCPPCLIDIR="'$GODOTCPPCLIDIR'"' >> ~/.bashrc
chmod u+x ./bin/gdev

source ~/.bashrc