#!/bin/bash
GDEV=$(pwd)

echo 'export PATH="'$GDEV'/bin:$PATH"' >> ~/.bashrc
echo 'export GDEV="'$GDEV'"' >> ~/.bashrc
chmod u+x ./bin/gdev

source ~/.bashrc

{
  node -v
} || {
  echo "Node not installed"
}